spring:
  application:
    name: learner-user-api
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    #    password: Learner@2023
    #    url: jdbc:mysql://34.29.125.76:3306,34.68.236.8:3306/learnerCrownClothing?useSSL=FALSE
    password: root
    url: jdbc:mysql://localhost:3306/product_managment?useSSL=FALSE
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8232
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    password: i27@project
    url: jdbc:mysql://i27project.mysql.database.azure.com/learnerCrownClothing
    username: i27project
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8232
eureka:
  client:
    serviceUrl:
      defaultZone: http://i27-eureka-dev.eureka-dev-ns.svc.cluster.local:80/eureka/
  instance:
    preferIpAddress: true
